server:
  port: 9001
  tomcat:
    connection-timeout: 2s  # предел времени, в течение которого Tomcat должен ждать между принятием TCP-соединения от клиента и фактическим получением HTTP-запроса.
    keep-alive-timeout: 15s # как долго соединение должно оставаться открытым в ожидании новых HTTP-запросов.
    threads:
      max: 50               # максимальное количество потоков обработки запросов может быть обработано одновременно.
      min-spare: 5          # минимальное количество потоков, которые всегда должны выполняться, создаваемых при запуске.

spring:
  datasource:
    username: postgres
    password: 7774256rom
    url: jdbc:postgresql://localhost:5434/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate

#  sql:
#    init:
#      mode: always
