server:
  port: 9001
  tomcat:
    connection-timeout: 2s  # предел времени, в течение которого Tomcat должен ждать между принятием TCP-соединения от клиента и фактическим получением HTTP-запроса.
    keep-alive-timeout: 15s # как долго соединение должно оставаться открытым в ожидании новых HTTP-запросов.
    threads:
      max: 50               # максимальное количество потоков обработки запросов может быть обработано одновременно.
      min-spare: 5          # минимальное количество потоков, которые всегда должны выполняться, создаваемых при запуске.